// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpkhdwugpnedkdaehvve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwa2hkd3VncG5lZGtkYWVodnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNTI1MDksImV4cCI6MjA4MzkyODUwOX0.2w6m1wWbUWQVT3aG02klvJnJE9ekP3_990m43zuYs7E";

const GUEST_SESSION_KEY = 'kindred-cards-guest-session';

// Get guest session ID for unauthenticated users
const getGuestSessionId = (): string | null => {
  if (typeof localStorage === 'undefined') return null;
  return localStorage.getItem(GUEST_SESSION_KEY);
};

// Custom fetch that adds guest session header for RLS policies (guest users only)
const customFetch = (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
  // Don't modify if no init or no headers - Supabase needs those
  if (!init || !init.headers) {
    return fetch(input, init);
  }

  // Check if Authorization header exists - if so, user is authenticated, don't modify
  const hasAuthHeader = (
    (init.headers instanceof Headers && init.headers.has('Authorization')) ||
    (typeof init.headers === 'object' && 'Authorization' in init.headers)
  );

  if (hasAuthHeader) {
    // User is authenticated, don't modify the request
    return fetch(input, init);
  }

  const guestSessionId = getGuestSessionId();
  if (!guestSessionId) {
    return fetch(input, init);
  }

  // Only add guest header for REST API calls (not storage or edge functions)
  const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
  if (url.includes('/functions/v1/') || url.includes('/storage/v1/')) {
    return fetch(input, init);
  }

  // Add guest session header for unauthenticated REST API calls
  // Preserve all existing headers (including apikey)
  let newHeaders: HeadersInit;

  if (init.headers instanceof Headers) {
    // Clone the Headers object and add our header
    const headers = new Headers(init.headers);
    headers.set('x-guest-session-id', guestSessionId);
    newHeaders = headers;
  } else if (Array.isArray(init.headers)) {
    // Headers as array of tuples
    newHeaders = [...init.headers, ['x-guest-session-id', guestSessionId]];
  } else if (typeof init.headers === 'object') {
    // Headers as plain object
    newHeaders = {
      ...init.headers,
      'x-guest-session-id': guestSessionId
    };
  } else {
    newHeaders = { 'x-guest-session-id': guestSessionId };
  }

  console.log('🔑 customFetch: Adding guest session header:', guestSessionId);
  return fetch(input, { ...init, headers: newHeaders });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: customFetch,
  },
});