// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngxvbmxhziirnxkycodx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5neHZibXhoemlpcm54a3ljb2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjQ1NzYsImV4cCI6MjA2NzMwMDU3Nn0.DejDxucc9ba4injVdpsn9QwQxTLFnDeJ0tF4BrorKN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (url, options: RequestInit = {}) => {
      try {
        const key = 'kindred-cards-guest-session';
        let sessionId = localStorage.getItem(key);
        if (!sessionId) {
          const array = new Uint8Array(16);
          crypto.getRandomValues(array);
          const randomString = Array.from(array, (b) => b.toString(16).padStart(2, '0')).join('');
          sessionId = `guest_${Date.now()}_${randomString}`;
          localStorage.setItem(key, sessionId);
        }

        const headers = new Headers(options.headers as HeadersInit | undefined);
        headers.set('x-guest-session-id', sessionId);
        
        // Ensure proper content type for REST API requests
        if (!headers.get('content-type') && url.includes('/rest/v1/')) {
          headers.set('content-type', 'application/json');
        }

        console.log('🔗 Supabase request with guest session:', { url: url.split('?')[0], sessionId });
        
        return fetch(url, { ...options, headers });
      } catch (error) {
        console.error('❌ Error in supabase client fetch:', error);
        return fetch(url, options);
      }
    },
  },
});